import {EventBus} from './core/EventBus.js';
import {DataManager} from './data/DataManager.js';
import {ProgressionSystem} from './progression/ProgressionSystem.js';
import {CombatEngine} from './combat/CombatEngineV2.js?v=6';
import {CombatUI} from './ui/CombatUI.js';
import {AdminUI} from './ui/AdminUI.js';
import {ProfileUI} from './ui/ProfileUI.js';
import {DungeonUI} from './ui/DungeonUI.js';
import {InventoryUI} from './ui/InventoryUI.js';
import {CraftingUI} from './ui/CraftingUI.js?v=4';
import {JobsUI} from './ui/JobsUI.js';
import {AutoBattlerHUD} from './ui/AutoBattlerHUD.js';
const data=new DataManager();await data.load();const bus=new EventBus();const progression=new ProgressionSystem({...data.progression,...data.balance.rewards,...data.balance.player,items:data.items,jobs:data.jobs},bus);const ui=new CombatUI(null,progression,data);const engine=new CombatEngine({data,bus,progression,ui});ui.engine=engine;new AdminUI(data,progression,engine,bus);const profile=new ProfileUI({progression,data,engine});new DungeonUI({data,engine,progression});new InventoryUI({progression,data,engine});new CraftingUI({progression,data});new JobsUI({progression,data});const autoHud=new AutoBattlerHUD({progression,data,engine});
let last=performance.now();function frame(now){const dt=Math.min(.1,(now-last)/1000);last=now;engine.update(dt);ui.render();ui.updateHud();autoHud.render();requestAnimationFrame(frame)}requestAnimationFrame(frame);
let restartTimer=null;function autoRestart(label){if(restartTimer)return;ui.setStatus(`${label} — restarting run…`);restartTimer=setTimeout(()=>{restartTimer=null;engine.restartRun()},1200)}
bus.on('waveStart',({wave})=>ui.setStatus(`Wave ${wave} — auto combat`));bus.on('waveClear',({wave})=>ui.setStatus(`Wave ${wave} cleared — recovery phase`));bus.on('levelUp',({level})=>{ui.log(`Level up! You are now level ${level}. +1 skill point.`);profile.render()});bus.on('lootFound',({item})=>ui.setStatus(`Loot found: ${item.icon} ${item.name}`));bus.on('inventoryChanged',()=>ui.updateHud());bus.on('classChanged',()=>{ui.setStatus(`${engine.currentClass().name} equipped.`);profile.render()});bus.on('victory',()=>autoRestart(`Victory! ${engine.dungeon.name} completed`));bus.on('defeat',()=>autoRestart('Defeat'));bus.on('runReset',()=>{ui.setStatus(`Run restarted at level ${progression.level}.`);document.getElementById('pauseBtn').textContent='Pause'});bus.on('dungeonChanged',()=>{ui.updateHud();ui.setStatus(`${engine.dungeon.name} selected — progression preserved.`)});bus.on('craftComplete',({item})=>ui.setStatus(`Crafted ${item.icon} ${item.name} with random affixes.`));bus.on('dungeonReward',({gold})=>ui.setStatus(`Dungeon reward claimed: +${gold} gold + equipment + materials.`));bus.on('jobAction',({jobId,action,levels})=>{const j=data.jobs.jobs[jobId];ui.setStatus(`${j.icon} ${j.name}: ${action.replaceAll('_',' ')} complete${levels?` · Job level +${levels}`:''}.`)});bus.on('farmChanged',({action,yields})=>{if(action==='harvest')ui.setStatus(`🌾 Harvest complete! ${Object.entries(yields||{}).map(([k,v])=>`+${v} ${k}`).join(' · ')}`)});bus.on('dataImported',()=>location.reload());
document.getElementById('pauseBtn').onclick=()=>{if(engine.active){engine.active=false;engine.state='paused';document.getElementById('pauseBtn').textContent='Resume';ui.setStatus('Paused')}else if(engine.state==='paused'){engine.active=true;engine.state='combat';document.getElementById('pauseBtn').textContent='Pause';ui.setStatus(`Wave ${engine.wave} — auto combat`)}};document.getElementById('restartBtn').onclick=()=>engine.restartRun();document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>{engine.setSpeed(+b.dataset.speed);document.querySelectorAll('[data-speed]').forEach(x=>x.classList.toggle('active',x===b))});console.info('[AutoBattler] V3 admin + forge glow + reward multipliers loaded');engine.start();
