import {downloadJson,readJson} from '../save/ExportManager.js';
export class AdminUI{
 constructor(data,progression,engine,bus){this.data=data;this.progression=progression;this.engine=engine;this.bus=bus;this.panel=document.getElementById('adminPanel');this.content=document.getElementById('adminContent');this.closeBtn=document.getElementById('closeAdminBtn');this.tab='balance';this.returnFocus=null;this.bind()}
 bind(){document.getElementById('adminBtn').onclick=()=>this.open();this.closeBtn.onclick=()=>this.close();this.panel.addEventListener('click',e=>{if(e.target===this.panel)this.close()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&this.panel.classList.contains('open')){e.preventDefault();this.close()}});document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');this.tab=b.dataset.tab;this.render()})}
 open(){this.returnFocus=document.activeElement;this.panel.classList.add('open');this.panel.removeAttribute('inert');this.panel.setAttribute('aria-hidden','false');this.render();requestAnimationFrame(()=>this.closeBtn?.focus())}
 close(){if(document.activeElement&&this.panel.contains(document.activeElement))document.activeElement.blur();this.panel.setAttribute('aria-hidden','true');this.panel.setAttribute('inert','');this.panel.classList.remove('open');requestAnimationFrame(()=>{if(this.returnFocus&&document.contains(this.returnFocus))this.returnFocus.focus();this.returnFocus=null})}
 render(){if(this.tab==='balance')this.renderBalance();if(this.tab==='enemies')this.renderEnemies();if(this.tab==='save')this.renderSave()}
 renderBalance(){const b=this.data.balance.combat,p=this.data.balance.player;this.content.innerHTML=`<div class="form-grid"><div class="field"><label>Wave delay <span id="wv">${b.waveDelay}s</span></label><input id="waveDelay" type="range" min="0.5" max="6" step="0.5" value="${b.waveDelay}"></div><div class="field"><label>Hero range <span id="rng">${p.attackRange}</span></label><input id="heroRange" type="range" min="150" max="450" step="10" value="${p.attackRange}"></div><div class="field"><label>Enemy damage variance</label><input id="enemyVar" type="number" min="0" max="1" step="0.01" value="${b.enemyDamageVariance}"></div><div class="field"><label>Hero damage variance</label><input id="heroVar" type="number" min="0" max="1" step="0.01" value="${b.heroDamageVariance}"></div></div>`;document.getElementById('waveDelay').oninput=e=>{b.waveDelay=+e.target.value;document.getElementById('wv').textContent=`${b.waveDelay}s`};document.getElementById('heroRange').oninput=e=>{p.attackRange=+e.target.value;document.getElementById('rng').textContent=p.attackRange};document.getElementById('enemyVar').oninput=e=>b.enemyDamageVariance=+e.target.value;document.getElementById('heroVar').oninput=e=>b.heroDamageVariance=+e.target.value}
 renderEnemies(){const list=Object.values(this.data.enemies);this.content.innerHTML=`<p class="note">Edit live config values. Changes apply to newly spawned units.</p>`+list.map(e=>`<div class="enemy-row"><strong>${e.icon} ${e.name}</strong><label>HP <input data-id="${e.id}" data-k="hp" type="number" value="${e.stats.hp}"></label><label>ATK <input data-id="${e.id}" data-k="attack" type="number" value="${e.stats.attack}"></label><label>AS <input data-id="${e.id}" data-k="attackSpeed" type="number" step="0.05" value="${e.stats.attackSpeed}"></label></div>`).join('');this.content.querySelectorAll('input').forEach(i=>i.onchange=()=>{const e=this.data.enemies[i.dataset.id];e.stats[i.dataset.k]=+i.value})}
 renderSave(){const bundle=this.data.exportBundle({player:{level:this.progression.level,xp:this.progression.xp,gold:this.progression.gold}});this.content.innerHTML=`<div class="save-grid"><div class="save-box"><h3>Export</h3><p class="note">Export game configuration and current progression as one JSON bundle.</p><button id="exportBtn">Export JSON</button></div><div class="save-box"><h3>Import</h3><p class="note">Import a previously exported bundle. No localStorage is used.</p><input id="importFile" type="file" accept="application/json,.json"></div></div><div class="save-box" style="margin-top:14px"><h3>Preview</h3><textarea readonly>${JSON.stringify(bundle,null,2)}</textarea></div>`;document.getElementById('exportBtn').onclick=()=>downloadJson('auto-battler-v1.json',bundle);document.getElementById('importFile').onchange=async e=>{try{const b=await readJson(e.target.files[0]);this.data.importBundle(b);this.bus.emit('dataImported');this.render();alert('Config imported. Restart the run to apply all changes.')}catch(err){alert(`Import failed: ${err.message}`)}}}
}
