export class CombatUI{
 constructor(engine,progression,data){this.engine=engine;this.progression=progression;this.data=data;this.el={battlefield:document.getElementById('battlefield'),hero:document.getElementById('heroSlot'),enemyLayer:document.getElementById('enemyLayer'),fx:document.getElementById('combatFx'),log:document.getElementById('log'),status:document.getElementById('combatStatus')};this.lastHp=new Map()}
 render(){this.el.hero.innerHTML='';if(this.engine.hero)this.renderUnit(this.el.hero,this.engine.hero);this.el.enemyLayer.innerHTML='';for(const e of this.engine.enemies)this.renderUnit(this.el.enemyLayer.appendChild(document.createElement('div')),e)}
 renderUnit(node,u){const old=this.lastHp.get(u.id);node.className='unit '+(u.team==='hero'?'hero-unit':'enemy')+(u.elite?' elite-unit':'')+(u.dead?' defeated':'');node.style.left=`${u.position}%`;const hp=Math.max(0,u.hp/u.maxHp*100);const effects=(u.effects||[]).map(e=>e.type==='poison'?'☠️':e.type==='enrage'?'🔥':'').join('');const elite=u.elite?'<span class="elite-badge">ELITE</span>':'';node.innerHTML=`${elite}<div class="unit-glow"></div><div class="unit-body">${u.team==='hero'?(this.data.classes[this.progression.classId]?.icon||'🏹'):u.template.icon}</div><div class="unit-name">${u.template.name} ${effects}</div><div class="bar"><i style="width:${hp}%"></i></div><small class="hp-text">${Math.ceil(Math.max(0,u.hp))} / ${Math.ceil(u.maxHp)}</small>`;if(old!=null&&u.hp<old)node.classList.add('taking-hit');this.lastHp.set(u.id,u.hp)}
 updateHud(){const p=this.progression,d=this.engine.dungeon;document.getElementById('waveLabel').textContent=`${this.engine.wave} / ${d.waves}`;document.getElementById('levelLabel').textContent=p.level;document.getElementById('goldLabel').textContent=p.gold;document.getElementById('bestWave').textContent=p.bestWave;document.getElementById('kills').textContent=p.totalKills;document.getElementById('damage').textContent=Math.floor(p.totalDamage);document.getElementById('dungeonName').textContent=d.name;const next=p.xpToNext();document.getElementById('xpFill').style.width=`${Math.min(100,p.xp/next*100)}%`;document.getElementById('xpLabel').textContent=`${p.xp} / ${next}`;const h=this.engine.hero,cls=this.data.classes[p.classId]||this.data.classes.ranger;if(h)document.getElementById('heroPanel').innerHTML=`<div class="hero-sheet"><div class="portrait">${cls.icon||'🏹'}</div><div><div><strong>${cls.name}</strong> · Lv ${p.level}</div><div class="stats"><div><span>HP</span><strong>${Math.ceil(h.hp)}/${Math.ceil(h.maxHp)}</strong></div><div><span>ATK</span><strong>${Math.round(h.attack)}</strong></div><div><span>DEF</span><strong>${Math.round(h.defense)}</strong></div><div><span>AS</span><strong>${h.attackSpeed.toFixed(2)}</strong></div></div></div></div>`;else{const b=cls.baseStats||{},g=cls.growth||{},at=k=>Number(b[k]||0)+(p.level-1)*Number(g[k]||0);document.getElementById('heroPanel').innerHTML=`<div class="hero-sheet"><div class="portrait">${cls.icon||'🏹'}</div><div><div><strong>${cls.name}</strong> · Lv ${p.level}</div><div class="stats"><div><span>HP</span><strong>${Math.ceil(at('hp'))}</strong></div><div><span>ATK</span><strong>${Math.round(at('attack'))}</strong></div><div><span>DEF</span><strong>${Math.round(at('defense'))}</strong></div><div><span>AS</span><strong>${Number(b.attackSpeed||1).toFixed(2)}</strong></div></div></div></div>`}const hasPoison=(cls.spellIds||[]).includes('poison_arrow');document.getElementById('spellPanel').innerHTML=hasPoison?`<div class="spell"><h4>☄️ ${this.data.spells.poison_arrow.name}</h4><small>Every ${this.data.spells.poison_arrow.cooldown}s: poison the nearest enemy for ${this.data.spells.poison_arrow.poisonDps}/s over ${this.data.spells.poison_arrow.poisonDuration}s.</small></div>`:`<div class="spell"><h4>🛡️ No active spell</h4><small>This class focuses on its core combat stats.</small></div>`;document.getElementById('classBadge').textContent=cls.name;document.getElementById('gameTime').textContent=this.formatTime(this.engine.elapsed)}
 formatTime(s){s=Math.floor(s);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 log(msg){this.el.log.textContent=msg;clearTimeout(this.logTimer);this.logTimer=setTimeout(()=>this.el.log.textContent='',3200)}
 fxAttack(attacker,target,kind,onHit){const el=document.createElement('div');el.className=`attack-fx attack-${kind}`;el.style.left=`${attacker.position}%`;el.style.bottom='115px';el.style.setProperty('--target-left',`${target.position}%`);if(kind==='arrow')el.innerHTML='<span class="arrow-shaft"></span><span class="arrow-head">➤</span>';else if(kind==='projectile')el.innerHTML='<i></i>';else el.innerHTML='<span class="slash-core">✦</span>';this.el.fx.appendChild(el);const duration=kind==='melee'?140:kind==='arrow'?280:240;setTimeout(()=>{el.remove();if(target&&!target.dead)this.fxImpact(target,kind);onHit()},duration)}
 fxImpact(target,kind){const impact=document.createElement('div');impact.className=`impact-ring ${kind==='melee'?'impact-slash':''}`;impact.style.left=`${target.position}%`;impact.style.bottom='115px';this.el.fx.appendChild(impact);setTimeout(()=>impact.remove(),420)}
 fxDamage(target,damage){this.fxText(target,damage)}fxCrit(target,damage){this.fxText(target,damage,true)}
 fxSpell(a,t){const el=document.createElement('div');el.className='projectile projectile-spell';el.style.left=`${a.position}%`;el.style.bottom='115px';el.style.setProperty('--target-x',`${t.position-a.position}vw`);el.innerHTML='<i></i>';this.el.fx.appendChild(el);setTimeout(()=>{el.remove();this.fxImpact(t,'spell')},260)}
 fxText(target,damage,crit=false){const el=document.createElement('div');el.className='damage-pop '+(crit?'crit-pop':'');el.textContent=`-${damage}${crit?'!':''}`;el.style.left=`${target.position}%`;el.style.bottom=crit?'160px':'150px';this.el.fx.appendChild(el);setTimeout(()=>el.remove(),750)}
 setStatus(text){this.el.status.textContent=text}
}
