export class FarmUI{
  constructor({progression,bus}){this.progression=progression;this.bus=bus;this.el=document.getElementById('farmPanel');this.grid=document.getElementById('farmGrid');this.info=document.getElementById('farmInfo');this.log=document.getElementById('farmLog');this.size=9;this.tick=0;this.selectedCrop='wheat';this.state=this.load();this.render()}
  load(){try{const raw=sessionStorage.getItem('farm-v33');if(raw)return JSON.parse(raw)}catch{}return {coins:0,level:1,xp:0,tiles:Array.from({length:81},(_,i)=>({id:i,crop:null,stage:0,watered:false,sprinkler:false,growth:0}))}}
  save(){try{sessionStorage.setItem('farm-v33',JSON.stringify(this.state))}catch{}}
  cropDefs(){return {wheat:{icon:'🌾',name:'Wheat',time:18,value:12,xp:8},carrot:{icon:'🥕',name:'Carrot',time:24,value:18,xp:11},corn:{icon:'🌽',name:'Corn',time:32,value:26,xp:15},potato:{icon:'🥔',name:'Potato',time:40,value:34,xp:20}}}
  render(){if(!this.grid)return;this.grid.innerHTML=this.state.tiles.map((t,i)=>{const x=i%this.size,y=Math.floor(i/this.size),crop=t.crop?this.cropDefs()[t.crop]:null,pct=crop?Math.min(100,Math.round(t.growth/crop.time*100)):0;return `<button class="farm-tile ${t.crop?'planted':''} ${t.watered?'watered':''} ${t.sprinkler?'has-sprinkler':''}" style="left:${x*62}px;top:${y*34}px" data-id="${i}" title="${crop?`${crop.name} ${pct}%`:'Empty soil'}"><span class="tile-soil"></span>${crop?`<span class="crop crop-${t.stage}">${crop.icon}</span><span class="crop-progress"><i style="width:${pct}%"></i></span>`:'<span class="plant-plus">+</span>'}${t.sprinkler?'<span class="sprinkler">💧</span>':''}</button>`}).join('');this.grid.querySelectorAll('.farm-tile').forEach(b=>b.onclick=()=>this.select(+b.dataset.id));this.renderInfo()}
  select(id){const t=this.state.tiles[id];if(!t.crop){t.crop=this.selectedCrop;t.stage=1;t.growth=0;t.watered=true;this.log.textContent=`🌱 ${this.cropDefs()[this.selectedCrop].name} planted and watered.`}else if(t.growth>=this.cropDefs()[t.crop].time){const c=this.cropDefs()[t.crop];this.state.coins+=c.value;this.state.xp+=c.xp;t.crop=null;t.stage=0;t.growth=0;t.watered=false;this.log.textContent=`🌾 Harvested ${c.name} · +${c.value}g · +${c.xp} XP`;this.bus?.emit('farmChanged',{action:'harvest',yields:{[c.name]:1}})}else{t.watered=true;this.log.textContent='💧 Soil watered. Growth boosted.'}this.save();this.render()}
  chooseCrop(crop){this.selectedCrop=crop;this.renderInfo();this.log.textContent=`Selected ${this.cropDefs()[crop].name} seeds.`}
  advance(dt){this.tick+=dt;if(this.tick<1)return;this.tick=0;let changed=false;for(const t of this.state.tiles){if(!t.crop)continue;const c=this.cropDefs()[t.crop];const boost=t.sprinkler?1.7:t.watered?1.25:.65;t.growth=Math.min(c.time,t.growth+boost);t.stage=t.growth/c.time>.75?3:t.growth/c.time>.4?2:1;t.watered=false;changed=true}if(changed){this.save();this.render()}}
  renderInfo(){const planted=this.state.tiles.filter(t=>t.crop).length,sprinklers=this.state.tiles.filter(t=>t.sprinkler).length;this.info.innerHTML=`<div><b>Farm Lv.${this.state.level}</b><span>${planted}/81 crops</span></div><div><b>💰 ${this.state.coins}g</b><span>💧 ${sprinklers} sprinklers</span></div><div class="farm-seeds">${Object.entries(this.cropDefs()).map(([id,c])=>`<button class="${this.selectedCrop===id?'active':''}" data-crop="${id}">${c.icon} ${c.name}</button>`).join('')}</div>`;this.info.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>this.chooseCrop(b.dataset.crop))}
  toggleSprinkler(){const empty=this.state.tiles.find(t=>!t.crop&&!t.sprinkler);if(!empty){this.log.textContent='No empty tile for a sprinkler.';return}empty.sprinkler=true;this.save();this.render();this.log.textContent='💦 Sprinkler placed. Crops on its tile grow faster.'}
}
