export class FarmUI{
  constructor({progression,bus}){this.progression=progression;this.bus=bus;this.el=document.getElementById('farmPanel');this.grid=document.getElementById('farmGrid');this.info=document.getElementById('farmInfo');this.log=document.getElementById('farmLog');this.size=6;this.tick=0;this.mode='plant';this.selectedCrop='wheat';this.sprinklerCost=50;this.render()}
  crops(){return this.progression.data.jobs?.farm?.crops||{}}
  farm(){return this.progression.farm||[]}
  crop(id){return this.crops()[id]}
  unlocked(c){return this.progression.level>=(c?.requiresLevel||1)}
  sprinklerCount(){return this.farm().filter(t=>t.sprinkler).length}
  nearbySprinkler(index){const x=index%this.size,y=Math.floor(index/this.size);return this.farm().some((t,i)=>{if(!t.sprinkler)return false;const sx=i%this.size,sy=Math.floor(i/this.size);return Math.max(Math.abs(x-sx),Math.abs(y-sy))<=1})}
  select(id){const t=this.farm()[id];if(!t)return;const now=Date.now();
    if(this.mode==='sprinkler'){this.placeSprinkler(id);return}
    if(this.mode==='plant'){if(t.crop){this.log.textContent='This plot is occupied. Switch to Harvest or Water.';return}const c=this.crop(this.selectedCrop);if(!this.unlocked(c)){this.log.textContent=`🔒 ${c?.name||'Crop'} unlocks at level ${c?.requiresLevel||1}.`;return}if((this.progression.materials[c.seed]||0)<1){this.log.textContent=`No ${c.seed} seeds. Buy seeds from the farm shop.`;return}if(this.progression.plantCrop(id,this.selectedCrop)){this.log.textContent=`🌱 ${c.name} planted.`;this.render()}return}
    if(this.mode==='water'){if(!t.crop){this.log.textContent='Water a planted crop.';return}if(t.readyAt<=now){this.log.textContent='🌾 This crop is ready to harvest.';return}this.progression.waterCrop(id,4);this.log.textContent=`💧 ${this.crop(t.crop).name} watered · growth accelerated.`;this.render();return}
    if(this.mode==='harvest'){if(!t.crop){this.log.textContent='Nothing to harvest here.';return}if(this.progression.harvestCrop(id)){const c=this.crop(t.crop);this.log.textContent=`🌾 Harvested ${c.name} · +${c.gold||0}g.`;this.render()}else this.log.textContent='⏳ Crop is still growing.'}
  }
  chooseCrop(id){const c=this.crop(id);if(!c)return;if(!this.unlocked(c)){this.log.textContent=`🔒 ${c.name} unlocks at level ${c.requiresLevel}.`;return}this.selectedCrop=id;this.mode='plant';this.render();this.log.textContent=`Selected ${c.icon} ${c.name} seeds.`}
  setMode(mode){this.mode=mode;this.renderInfo();this.log.textContent=mode==='plant'?'Select a crop, then click empty soil.':mode==='water'?'Water crops to accelerate growth.':mode==='harvest'?'Harvest mature crops for materials, gold and Farmer XP.':'Place a sprinkler on empty soil; it waters nearby plots automatically.'}
  placeSprinkler(id){const t=this.farm()[id];if(!t||t.crop||t.sprinkler){this.log.textContent='Choose an empty soil tile for the sprinkler.';return}const cost=this.sprinklerCost+this.sprinklerCount()*25;if(this.progression.gold<cost){this.log.textContent=`💦 Sprinkler costs ${cost}g.`;return}this.progression.gold-=cost;t.sprinkler=true;this.bus?.emit('farmChanged',{plot:id,action:'sprinkler'});this.bus?.emit('progressionChanged');this.log.textContent=`💦 Sprinkler placed · radius 1 · ${cost}g.`;this.render()}
  buySeeds(id){const c=this.crop(id);if(!c||!this.unlocked(c))return;const cost=Number(c.seedCost||6);if(this.progression.gold<cost){this.log.textContent=`Not enough gold for ${c.name} seeds.`;return}this.progression.gold-=cost;this.progression.materials[c.seed]=(this.progression.materials[c.seed]||0)+1;this.bus?.emit('materialsChanged');this.bus?.emit('progressionChanged');this.log.textContent=`🛒 Bought 1 ${c.seed} seed for ${cost}g.`;this.render()}
  advance(dt){this.tick+=dt;if(this.tick<1)return;this.tick=0;const now=Date.now();let changed=false;this.farm().forEach((t,i)=>{if(!t.crop)return;if(this.nearbySprinkler(i)&&t.readyAt>now){t.readyAt=Math.max(now,t.readyAt-900);t.wateredUntil=now+3500;changed=true}});if(changed)this.render()}
  render(){if(!this.grid)return;const farm=this.farm(),now=Date.now();this.grid.innerHTML=farm.map((t,i)=>{const c=t.crop?this.crop(t.crop):null;const pct=c?Math.min(100,Math.max(0,Math.round((1-(t.readyAt-now)/(c.growSeconds*1000))*100))):0;const ready=c&&t.readyAt<=now;const sprinkler=t.sprinkler;const irrigated=c&&this.nearbySprinkler(i);return `<button class="farm-tile ${c?'planted':''} ${ready?'ready':''} ${t.wateredUntil>now?'watered':''} ${sprinkler?'has-sprinkler':''} ${irrigated?'irrigated':''}" data-id="${i}" title="${c?`${c.name} · ${ready?'Ready':pct+'%'}`:'Empty soil'}"><span class="tile-soil"></span>${c?`<span class="crop crop-${Math.min(3,Math.ceil(pct/34))}">${c.icon}</span><span class="crop-progress"><i style="width:${pct}%"></i></span><span class="tile-status">${ready?'READY':pct+'%'}</span>`:'<span class="plant-plus">+</span>'}${sprinkler?'<span class="sprinkler">💧</span>':''}</button>`}).join('');this.grid.querySelectorAll('.farm-tile').forEach(b=>b.onclick=()=>this.select(+b.dataset.id));this.renderInfo()}
  renderInfo(){const farm=this.farm(),planted=farm.filter(t=>t.crop).length,ready=farm.filter(t=>t.crop&&t.readyAt<=Date.now()).length,sprinklers=this.sprinklerCount(),farmer=this.progression.jobs?.farmer||{level:1,xp:0};const crops=Object.entries(this.crops());this.info.innerHTML=`<div><b>Farmer Lv.${farmer.level}</b><span>${farmer.xp} XP</span></div><div><b>🌱 ${planted}/36 planted</b><span>🌾 ${ready} ready</span></div><div><b>💰 ${this.progression.gold}g</b><span>💦 ${sprinklers} sprinklers</span></div><div class="farm-modes"><button data-mode="plant" class="${this.mode==='plant'?'active':''}">🌱 Plant</button><button data-mode="water" class="${this.mode==='water'?'active':''}">💧 Water</button><button data-mode="harvest" class="${this.mode==='harvest'?'active':''}">🌾 Harvest</button><button data-mode="sprinkler" class="${this.mode==='sprinkler'?'active':''}">💦 Sprinkler</button></div><div class="farm-seeds">${crops.map(([id,c])=>{const stock=this.progression.materials[c.seed]||0;const lock=!this.unlocked(c);return `<div class="seed-card ${lock?'locked':''} ${this.selectedCrop===id?'active':''}"><button data-crop="${id}" ${lock?'disabled':''}>${c.icon} ${c.name}<small>${lock?'Lv.'+c.requiresLevel:stock+' seeds · '+c.growSeconds+'s'}</small></button><button class="seed-buy" data-buy="${id}" ${lock?'disabled':''}>+1 · ${c.seedCost||6}g</button></div>`}).join('')}</div>`;this.info.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>this.setMode(b.dataset.mode));this.info.querySelectorAll('[data-crop]').forEach(b=>b.onclick=()=>this.chooseCrop(b.dataset.crop));this.info.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>this.buySeeds(b.dataset.buy))}
}
