export class InventoryUI {
  constructor({progression,data,engine}){this.progression=progression;this.data=data;this.engine=engine;this.panel=document.getElementById('inventoryPanel');this.content=document.getElementById('inventoryContent');this.returnFocus=null;document.getElementById('inventoryBtn').onclick=()=>this.open();document.getElementById('closeInventoryBtn').onclick=()=>this.close();this.panel.addEventListener('click',e=>{if(e.target===this.panel)this.close()});progression.bus?.on?.('inventoryChanged',()=>{if(this.panel.classList.contains('open'))this.render()})}
  open(){this.returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;this.panel.inert=false;this.render();this.panel.classList.add('open');this.panel.setAttribute('aria-hidden','false');document.getElementById('closeInventoryBtn')?.focus()}
  close(){const target=this.returnFocus;this.panel.classList.remove('open');if(this.panel.contains(document.activeElement))document.activeElement.blur();this.panel.inert=true;this.panel.setAttribute('aria-hidden','true');if(target?.isConnected)target.focus();this.returnFocus=null}
  rarityRank(rarity){return ({mythic:6,legendary:5,epic:4,rare:3,uncommon:2,common:1}[String(rarity||'common').toLowerCase()]||0)}
  score(value){return this.progression.equipmentScore?.(value)||0}
  sorted(values){return values.map((value,index)=>({value,index,item:this.progression.resolveItem(value)})).filter(x=>x.item).sort((a,b)=>{const scoreDelta=this.score(b.value)-this.score(a.value);if(Math.abs(scoreDelta)>0.001)return scoreDelta;const rarity=this.rarityRank(b.item.rarity)-this.rarityRank(a.item.rarity);if(rarity)return rarity;return String(a.item.name).localeCompare(String(b.item.name))})}
  stats(item){return Object.entries(item.stats||{}).map(([k,v])=>`${k} +${typeof v==='number'&&v<1?Math.round(v*100)+'%':v}`).join(' · ')}
  render(){const p=this.progression,items=p.inventory||[],eq=p.equipment||{};const equipped=this.sorted(Object.values(eq).filter(Boolean)).map(({value,item})=>{const slot=item.slot||Object.entries(eq).find(([,v])=>v===value)?.[0]||'';return `<div class="inventory-item equipped-item"><div class="inventory-icon">${item.icon}</div><div class="inventory-copy"><strong>${item.name}</strong><span>${item.rarity} · ${slot} · Score ${this.score(value).toFixed(0)}</span><small>${this.stats(item)}</small></div><button data-unequip="${slot}">Unequip</button></div>`}).join('');const bag=this.sorted(items).map(({value,index,item})=>{const compare=p.compareEquipment?.(value)||{state:'equal',delta:0};const action=item.slot?`<button data-equip="${index}">Equip</button>`:'';return `<div class="inventory-item"><div class="inventory-icon">${item.icon}</div><div class="inventory-copy"><strong>${item.name}</strong><span>${item.rarity} · ${item.slot||'Material'} · Score ${this.score(value).toFixed(0)}</span><small>${this.stats(item)}</small>${item.description?`<small class="inventory-desc">${item.description}</small>`:''}${item.slot?`<em class="inventory-compare ${compare.state}">${compare.state==='better'?'▲ Better than equipped':compare.state==='worse'?'▼ Below equipped':'＝ Similar to equipped'}</em>`:''}</div>${action}</div>`}).join('');this.content.innerHTML=`<div class="inventory-toolbar"><div><span class="eyebrow">LOOT & EQUIPMENT</span><h3>Inventory</h3><p>Best equipment is always listed first by actual combat score.</p></div><div class="inventory-count"><strong>${items.length}</strong><span>items</span></div></div><div class="inventory-summary"><span>⚔️ ${this.score(eq.weapon).toFixed(0)} weapon</span><span>🛡️ ${this.score(eq.armor).toFixed(0)} armor</span><span>💍 ${this.score(eq.ring).toFixed(0)} ring</span><span>★ ${p.skillPoints} skill points</span></div><section class="inventory-section"><div class="inventory-section-head"><h4>Equipped</h4><span>${Object.values(eq).filter(Boolean).length} / 3 slots</span></div><div class="inventory-list">${equipped||'<p class="note">No equipment equipped.</p>'}</div></section><section class="inventory-section"><div class="inventory-section-head"><h4>Bag</h4><span>Best → worst</span></div><div class="inventory-list">${bag||'<p class="note">Your inventory is empty. Defeat enemies to find loot.</p>'}</div></section>`;this.content.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{if(p.equipItem(Number(b.dataset.equip)))this.render()});this.content.querySelectorAll('[data-unequip]').forEach(b=>b.onclick=()=>{if(p.unequipItem(b.dataset.unequip))this.render()})}
}
