export class ProfileUI {
  constructor({progression,data,engine}){this.progression=progression;this.data=data;this.engine=engine;this.panel=document.getElementById('profilePanel');this.content=document.getElementById('profileContent');document.getElementById('profileBtn').onclick=()=>this.open();document.getElementById('closeProfileBtn').onclick=()=>this.close();this.panel.addEventListener('click',e=>{if(e.target===this.panel)this.close()})}
  open(){this.render();this.panel.classList.add('open');this.panel.setAttribute('aria-hidden','false')}
  close(){this.panel.classList.remove('open');this.panel.setAttribute('aria-hidden','true')}
  render(){const p=this.progression,hero=this.engine.hero,cls=this.data.classes[p.classId]||this.data.classes.ranger,level=p.level,base=cls.baseStats||{},growth=cls.growth||{};const stat=k=>Number(base[k]||0)+(level-1)*Number(growth[k]||0);const hpMax=hero?Math.ceil(hero.maxHp):Math.ceil(stat('hp')),hpCurrent=hero?Math.ceil(hero.hp):hpMax,xpNext=p.xpToNext();this.content.innerHTML=`
    <div class="profile-hero"><div class="profile-portrait">${cls.icon||'🏹'}</div><div><div class="eyebrow">CHARACTER PROFILE</div><h3>${cls.name}</h3><span class="badge">Level ${level} · ${cls.role}</span><div class="profile-xp"><div><span>XP</span><strong>${p.xp} / ${xpNext}</strong></div><div class="xpbar"><i style="width:${Math.min(100,p.xp/xpNext*100)}%"></i></div></div></div></div>
    <h3 style="margin:18px 0 8px">Choose class</h3><div class="dungeon-content">${Object.values(this.data.classes).map(c=>`<button class="dungeon-card ${c.id===p.classId?'selected':''}" data-class="${c.id}"><div class="dungeon-icon">${c.icon||'⚔️'}</div><div class="dungeon-copy"><strong>${c.name}</strong><span>${c.role}</span><small>${c.description||''}</small></div><div class="dungeon-state">${c.id===p.classId?'Equipped':'Equip'}</div></button>`).join('')}</div>
    <div class="profile-grid">${this.statCard('HP',`${hpCurrent} / ${hpMax}`,`+${growth.hp||0} / level`)}${this.statCard('Attack',Math.round(stat('attack')),`+${growth.attack||0} / level`)}${this.statCard('Defense',Math.round(stat('defense')),`+${growth.defense||0} / level`)}${this.statCard('Attack speed',Number(base.attackSpeed||1).toFixed(2),'attacks / sec')}${this.statCard('Crit chance',`${Math.round(Number(base.critChance||0)*100)}%`,'critical hit chance')}${this.statCard('Crit damage',`${Number(base.critDamage||1.5).toFixed(2)}x`,'critical multiplier')}${this.statCard('Range',Math.round(Number(base.range||50)),'combat range')}${this.statCard('Gold',p.gold,'persistent')}</div>
    <div class="profile-run"><div><span>Total kills</span><strong>${p.totalKills}</strong></div><div><span>Total damage</span><strong>${Math.floor(p.totalDamage)}</strong></div><div><span>Best wave</span><strong>${p.bestWave}</strong></div></div>
    <p class="note">Restarting or changing dungeon resets only the combat run. Level, XP, gold, class and stats are preserved.</p>`;this.content.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{this.engine.selectClass(b.dataset.class);this.render()})}
  statCard(label,value,note){return `<div class="profile-stat"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`}
}
