export class ProfileUI {
  constructor({progression,data,engine}){this.progression=progression;this.data=data;this.engine=engine;this.panel=document.getElementById('profilePanel');this.content=document.getElementById('profileContent');this.returnFocus=null;this.selectedSlot=null;document.getElementById('profileBtn').onclick=()=>this.open();document.getElementById('closeProfileBtn').onclick=()=>this.close();this.panel.addEventListener('click',e=>{if(e.target===this.panel)this.close()});progression.bus?.on?.('inventoryChanged',()=>{this.updateBadge();if(this.panel.classList.contains('open'))this.render()});progression.bus?.on?.('skillChanged',()=>{this.updateBadge();if(this.panel.classList.contains('open'))this.render()});progression.bus?.on?.('levelUp',()=>{this.updateBadge();if(this.panel.classList.contains('open'))this.render()});this.updateBadge()}
  open(){this.returnFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;this.panel.inert=false;this.render();this.panel.classList.add('open');this.panel.setAttribute('aria-hidden','false');document.getElementById('closeProfileBtn')?.focus()}
  close(){const target=this.returnFocus;this.panel.classList.remove('open');if(this.panel.contains(document.activeElement))document.activeElement.blur();this.panel.inert=true;this.panel.setAttribute('aria-hidden','true');if(target?.isConnected)target.focus();this.returnFocus=null;this.selectedSlot=null}
  itemOf(value){return this.progression.resolveItem(value)}
  rarityRank(r){return ({mythic:6,legendary:5,epic:4,rare:3,uncommon:2,common:1}[String(r||'common').toLowerCase()]||0)}
  sortedEquipment(values){return values.map((value,index)=>({value,index,item:this.itemOf(value)})).filter(x=>x.item).sort((a,b)=>{const d=this.progression.equipmentScore(b.value)-this.progression.equipmentScore(a.value);if(Math.abs(d)>.001)return d;const r=this.rarityRank(b.item.rarity)-this.rarityRank(a.item.rarity);return r||String(a.item.name).localeCompare(String(b.item.name))})}
  upgradeForSlot(slot){const current=this.progression.equipment?.[slot],score=this.progression.equipmentScore?.(current)||0;return this.sortedEquipment(this.progression.inventory||[]).some(x=>x.item?.slot===slot&&(this.progression.equipmentScore?.(x.value)||0)>score+.5)}
  hasUpgrade(){return Number(this.progression.skillPoints||0)>0||['weapon','armor','ring'].some(s=>this.upgradeForSlot(s))}
  updateBadge(){const b=document.getElementById('profileBtn');if(!b)return;const ready=this.hasUpgrade();b.classList.toggle('has-upgrade',ready);b.dataset.upgrade=ready?'true':'false';b.title=ready?'Upgrade available on Character page':''}
  statText(i){return Object.entries(i?.stats||{}).map(([k,v])=>`${k} +${typeof v==='number'&&v<1?Math.round(v*100)+'%':v}`).join(' · ')}
  compare(v){return this.progression.compareEquipment(v)}
  comparison(v){const c=this.compare(v);return `<span class="equip-quality ${c.state}">${c.state==='better'?'▲ Better':c.state==='worse'?'▼ Worse':'＝ Similar'}${c.delta?` · ${Math.abs(c.delta).toFixed(0)} score`:''}</span>`}
  render(){
    const p=this.progression,cls=this.data.classes[p.classId]||this.data.classes.ranger,hero=this.engine.hero,base=cls.baseStats||{},growth=cls.growth||{},eq=p.equipmentStats?.()||{},level=p.level;
    const calc=k=>Number(base[k]||0)+(level-1)*Number(growth[k]||0);const hpMax=Math.ceil(hero?.maxHp??(calc('hp')+(p.skills.vitality||0)*25+(eq.hp||0)));const hpCurrent=Math.min(hpMax,Math.ceil(hero?.hp??hpMax));const attack=Math.round(calc('attack')+(p.skills.power||0)*5+(eq.attack||0));const defense=Math.round(calc('defense')+(eq.defense||0));const speed=Number(base.attackSpeed||1)+(p.skills.haste||0)*.08+(eq.attackSpeed||0);const crit=Math.round((Number(base.critChance||0)+(p.skills.precision||0)*.02+(eq.critChance||0))*100);const critDamage=(Number(base.critDamage||1.5)+(eq.critDamage||0)).toFixed(2);const range=Math.round(base.range||50);const xpNext=p.xpToNext(),xpPct=Math.min(100,p.xp/xpNext*100);const equipped=Object.values(p.equipment||{}).filter(Boolean).length;
    const slots={weapon:'⚔',armor:'🛡',ring:'💍'};const slotCard=slot=>{const value=p.equipment?.[slot],item=this.itemOf(value),upgrade=this.upgradeForSlot(slot),selected=this.selectedSlot===slot;return `<button class="paper-slot ${slot} ${item?'filled':''} ${selected?'selected':''} ${upgrade?'has-upgrade':''}" data-slot="${slot}"><span class="paper-slot-glyph">${item?.icon||slots[slot]}</span><strong>${item?.name||'Empty'}</strong><small>${item?.rarity||'Empty'} · ${slot}</small>${item?`<em>${this.progression.equipmentScore(value).toFixed(0)} score</em>`:''}${upgrade?'<i class="slot-upgrade">+</i>':''}</button>`};
    const candidates=this.selectedSlot?this.sortedEquipment(p.inventory||[]).filter(x=>x.item?.slot===this.selectedSlot):[];const chooser=this.selectedSlot?`<div class="equipment-chooser"><div class="chooser-head"><strong>${this.selectedSlot.toUpperCase()} · SELECT EQUIPMENT</strong><button data-close-chooser>Close</button></div>${candidates.length?`<div class="equipment-choice-list">${candidates.map(({value,index,item})=>`<button class="equipment-choice" data-equip="${index}"><span class="choice-icon">${item.icon}</span><span><strong>${item.name}</strong><small>${item.rarity} · ${this.progression.equipmentScore(value).toFixed(0)} score</small>${this.comparison(value)}</span><b>Equip</b></button>`).join('')}</div>`:'<p class="note">No equipment available for this slot.</p>'}</div>`:'';
    const primary=[['Vitality',hpMax,'HP'],['Attack',attack,'Damage'],['Defense',defense,'Mitigation'],['Attack speed',speed.toFixed(2),'Hits / sec'],['Critical',`${crit}%`,'Chance'],['Crit damage',`${critDamage}x`,'Multiplier'],['Range',range,'Distance']];const secondary=[['Dodge',`${Math.min(95,50+Math.round(defense*1.5))}%`],['Tackle',`${Math.min(95,25+Math.round(defense*1.2))}%`],['Prospecting','100'],['Wisdom',Math.floor(Math.max(0,level-1)/5)],['Kamas',p.gold.toLocaleString()]];
    const skills=[['power','Power','+5 Attack / rank','⚔'],['vitality','Vitality','+25 HP / rank','♥'],['haste','Haste','+0.08 Attack speed / rank','⚡'],['precision','Precision','+2% Crit / rank','✦']];
    this.content.innerHTML=`<div class="character-hero-banner"><div class="portrait-large">${cls.icon||'🏹'}</div><div class="character-identity"><span class="eyebrow">HERO PROFILE · ${cls.role?.toUpperCase()||'ADVENTURER'}</span><h3>${cls.name}</h3><div class="identity-badges"><span class="badge">LEVEL ${level}</span><span class="badge purple">${equipped}/3 EQUIPPED</span><span class="badge green">${p.skillPoints} SKILL POINTS</span></div><div class="profile-xp"><div><span>Experience</span><strong>${p.xp.toLocaleString()} / ${xpNext.toLocaleString()}</strong></div><div class="xpbar"><i style="width:${xpPct}%"></i></div></div></div><div class="power-rating"><span>COMBAT POWER</span><strong>${Math.round(attack+defense*2+speed*80+crit*2)}</strong><small>ATK ${attack} · DEF ${defense}</small></div></div>
    <div class="character-main-grid"><section class="paper-doll-panel"><div class="profile-section-title"><h3>Equipment</h3><span class="badge">PAPER DOLL</span></div><div class="paper-doll"><div class="paper-col left"><div class="paper-label">WEAPON</div>${slotCard('weapon')}<div class="paper-label">RING</div>${slotCard('ring')}</div><div class="paper-figure"><div class="figure-halo"></div><div class="figure-shadow"></div><div class="figure-body"><span class="figure-head">${cls.icon||'🧙'}</span><span class="figure-chest">✦</span><span class="figure-legs">▥</span></div><div class="figure-class">${cls.name}</div><div class="figure-level">LEVEL ${level}</div></div><div class="paper-col right"><div class="paper-label">ARMOR</div>${slotCard('armor')}<div class="paper-label">POWER</div><div class="mini-power"><strong>${Math.round(attack+defense*2)}</strong><span>Gear + stats</span></div></div></div>${chooser}<div class="equipment-summary"><span>Gear bonuses</span><strong>+${eq.attack||0} ATK · +${eq.hp||0} HP · +${eq.defense||0} DEF · +${Math.round((eq.critChance||0)*100)}% CRIT</strong></div></section>
    <section class="stats-panel"><div class="profile-section-title"><h3>Characteristics</h3><span>Final values</span></div><div class="primary-stats">${primary.map(([n,v,s])=>`<div class="big-stat"><span>${n}</span><strong>${v}</strong><small>${s}</small></div>`).join('')}</div><div class="profile-section-title sub"><h3>Secondary</h3><span>Derived</span></div><div class="secondary-stats">${secondary.map(([n,v])=>`<div><span>${n}</span><strong>${v}</strong></div>`).join('')}</div></section></div>
    <section class="profile-section"><div class="profile-section-title"><h3>Class & abilities</h3><span>${cls.description||''}</span></div><div class="class-summary"><div class="class-emblem">${cls.icon||'⚔'}</div><div><strong>${cls.name} · ${cls.role}</strong><p>${cls.description||'Specialized auto-battler combat class.'}</p></div></div><div class="skill-tree">${skills.map(([id,name,note,icon])=>{const rank=p.skills[id]||0;return `<button class="skill-node ${rank?'unlocked':''} ${p.skillPoints?'upgrade-ready':''}" data-skill="${id}" ${p.skillPoints<1?'disabled':''}><div class="skill-node-icon">${icon}</div><div><strong>${name}</strong><small>${note}</small></div><b>RANK ${rank}</b>${p.skillPoints?'<span class="upgrade-badge">+</span>':''}</button>`}).join('')}</div></section>
    <section class="profile-section"><div class="profile-section-title"><h3>Class selection</h3><span>Switch class while keeping progression</span></div><div class="class-grid">${Object.values(this.data.classes).map(c=>`<button class="class-card ${c.id===p.classId?'selected':''}" data-class="${c.id}"><div class="class-card-icon">${c.icon||'⚔️'}</div><div><strong>${c.name}</strong><small>${c.role}</small><p>${c.description||''}</p></div>${c.id===p.classId?'<span class="equipped-mark">✓</span>':''}</button>`).join('')}</div></section>
    <section class="profile-section"><div class="profile-section-title"><h3>Lifetime</h3><span>Persistent progression</span></div><div class="achievement-grid"><div><strong>${p.totalKills.toLocaleString()}</strong><small>Monsters defeated</small></div><div><strong>${Math.floor(p.totalDamage).toLocaleString()}</strong><small>Damage dealt</small></div><div><strong>${p.bestWave}</strong><small>Best wave</small></div><div><strong>${p.inventory?.length||0}</strong><small>Items collected</small></div></div></section>`;
    this.content.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{this.selectedSlot=this.selectedSlot===b.dataset.slot?null:b.dataset.slot;this.render()});this.content.querySelectorAll('[data-equip]').forEach(b=>b.onclick=e=>{e.stopPropagation();if(p.equipItem(Number(b.dataset.equip))){this.selectedSlot=null;this.updateBadge();this.render()}});this.content.querySelector('[data-close-chooser]')?.addEventListener('click',()=>{this.selectedSlot=null;this.render()});this.content.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{this.engine.selectClass(b.dataset.class);this.updateBadge();this.render()});this.content.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{if(this.progression.buySkill(b.dataset.skill)){this.engine.restartRun();this.updateBadge();this.render()}});
  }
}