export class ProgressionSystem {
  constructor(data,bus){this.data=data;this.bus=bus;this.level=1;this.xp=0;this.gold=Number(this.data.startingGold||0);this.totalKills=0;this.totalDamage=0;this.bestWave=0;this.classId='ranger';this.skillPoints=0;this.skills={power:0,vitality:0,haste:0,precision:0};this.inventory=[];this.equipment={weapon:'training_bow',armor:null,ring:null};this.materials={scrap:0,crystal:0,ember:0,grain:8,herb:4,moonleaf:0};this.jobs={farmer:{level:1,xp:0},alchemist:{level:1,xp:0},miner:{level:1,xp:0},woodcutter:{level:1,xp:0}};this.farm=this.createFarm()}
  createFarm(){return Array.from({length:36},()=>({crop:null,plantedAt:0,readyAt:0,wateredUntil:0,sprinkler:false}))}
  xpToNext(){return Math.floor(this.data.xpBase*Math.pow(this.data.xpGrowth,this.level-1))}
  gain(xp,gold){const xpMultiplier=Number(this.data.xpMultiplier??this.data.waveXpMultiplier??1);this.xp+=Math.floor(xp*xpMultiplier);this.gold+=Math.floor(gold*(this.data.waveGoldMultiplier??1));this.checkLevel();this.bus.emit('progressionChanged')}
  checkLevel(){let leveled=false;while(this.xp>=this.xpToNext()){this.xp-=this.xpToNext();this.level++;this.skillPoints++;leveled=true}if(leveled)this.bus.emit('levelUp',{level:this.level})}
  selectClass(id){if(typeof id!=='string'||!id)return false;this.classId=id;this.bus.emit('classChanged',{classId:id});this.bus.emit('progressionChanged');return true}
  buySkill(id){const max=5;if(!(id in this.skills)||this.skillPoints<1||this.skills[id]>=max)return false;this.skills[id]++;this.skillPoints--;this.bus.emit('skillChanged',{skillId:id});this.bus.emit('progressionChanged');return true}
  resolveItem(value){return typeof value==='string'?this.data.items?.[value]:this.data.items?.[value?.baseId]||value}
  itemId(value){return typeof value==='string'?value:value?.baseId}
  addLoot(itemId){if(!this.data.items?.[itemId])return false;this.inventory.push(itemId);this.bus.emit('lootFound',{item:this.data.items[itemId]});this.bus.emit('inventoryChanged');return true}
  addMaterials(gain){for(const [k,v] of Object.entries(gain||{}))this.materials[k]=(this.materials[k]||0)+Number(v||0);this.bus.emit('materialsChanged');this.bus.emit('progressionChanged')}
  canCraft(recipe){if(!recipe)return false;for(const [k,v] of Object.entries(recipe.cost||{})){if(k==='gold'?this.gold<v:(this.materials[k]||0)<v)return false}return true}
  craft(recipe){if(!this.canCraft(recipe))return false;for(const [k,v] of Object.entries(recipe.cost||{})){if(k==='gold')this.gold-=v;else this.materials[k]-=v}const base=this.data.items?.[recipe.baseItemId];if(!base)return false;const affixPool=[{name:'Mighty',stat:'attack',min:.08,max:.18},{name:'Vital',stat:'hp',min:.08,max:.22},{name:'Keen',stat:'critChance',min:.02,max:.05},{name:'Swift',stat:'attackSpeed',min:.04,max:.12}];const rolls=Math.random()<.35?2:1;const stats={...(base.stats||{})};const affixes=[];for(let i=0;i<rolls;i++){const a=affixPool[Math.floor(Math.random()*affixPool.length)];const raw=a.min+Math.random()*(a.max-a.min);const add=a.stat==='critChance'||a.stat==='attackSpeed'?Number(raw.toFixed(3)):Math.max(1,Math.round((base.stats?.[a.stat]||10)*raw));stats[a.stat]=(stats[a.stat]||0)+add;affixes.push(`${a.name} ${a.stat==='critChance'||a.stat==='attackSpeed'?Math.round(add*100)+'%':'+'+add}`)}this.inventory.push({baseId:base.id,name:`${affixes.join(' ')} ${base.name}`,icon:base.icon,slot:base.slot,rarity:base.rarity,stats,description:`Crafted item · ${affixes.join(' · ')}`});this.bus.emit('craftComplete',{item:base});this.bus.emit('inventoryChanged');this.bus.emit('materialsChanged');this.bus.emit('progressionChanged');return true}
  equipmentScore(value){const item=this.resolveItem(value);if(!item)return 0;const s=item.stats||{};return Number(s.attack||0)*5+Number(s.hp||0)*.35+Number(s.defense||0)*3+Number(s.critChance||0)*220+Number(s.critDamage||0)*40+Number(s.attackSpeed||0)*120}
  compareEquipment(value){const item=this.resolveItem(value);if(!item)return {state:'equal',delta:0,score:0,currentScore:0};const current=this.equipment?.[item.slot];const score=this.equipmentScore(value),currentScore=this.equipmentScore(current),delta=score-currentScore;return {state:delta>.5?'better':delta<-.5?'worse':'equal',delta,score,currentScore,current:this.resolveItem(current)} }
  equipItem(index){const value=this.inventory[index],item=this.resolveItem(value);if(!item)return false;const old=this.equipment[item.slot];this.equipment[item.slot]=value;if(old)this.inventory[index]=old;else this.inventory.splice(index,1);this.bus.emit('inventoryChanged');this.bus.emit('progressionChanged');return true}
  equipValue(value){const index=this.inventory.findIndex(v=>v===value||this.itemId(v)===this.itemId(value));return index<0?false:this.equipItem(index)}
  unequipItem(slot){const id=this.equipment[slot];if(!id)return false;this.inventory.push(id);this.equipment[slot]=null;this.bus.emit('inventoryChanged');this.bus.emit('progressionChanged');return true}
  equipmentStats(){const out={};for(const value of Object.values(this.equipment)){const item=this.resolveItem(value);for(const [k,v] of Object.entries(item?.stats||{}))out[k]=(out[k]||0)+Number(v)}return out}
  jobXpToNext(id){const j=this.jobs[id]||{level:1};return Math.floor(35*Math.pow(1.32,j.level-1))}
  performJob(jobId,action){const job=this.data.jobs?.jobs?.[jobId],a=job?.actions?.find(x=>x.id===action);if(!job||!a)return false;const progress=this.jobs[jobId]||(this.jobs[jobId]={level:1,xp:0});if(this.level<(a.requiresLevel||1))return false;for(const [k,v] of Object.entries(a.cost||{}))if((this.materials[k]||0)<v)return false;for(const [k,v] of Object.entries(a.cost||{}))this.materials[k]-=v;for(const [k,v] of Object.entries(a.yields||{}))this.materials[k]=(this.materials[k]||0)+v;progress.xp+=a.xp;let levels=0;while(progress.xp>=this.jobXpToNext(jobId)){progress.xp-=this.jobXpToNext(jobId);progress.level++;levels++}this.bus.emit('jobAction',{jobId,action:a.id,levels,yields:a.yields});this.bus.emit('materialsChanged');this.bus.emit('progressionChanged');return true}
  plantCrop(plot,crop){const c=this.data.jobs?.farm?.crops?.[crop];const slot=this.farm[plot];if(!c||!slot||slot.crop)return false;if(this.level<(c.requiresLevel||1)||(this.materials[c.seed]||0)<1)return false;this.materials[c.seed]--;const now=Date.now();this.farm[plot]={crop,plantedAt:now,readyAt:now+c.growSeconds*1000,wateredUntil:0,sprinkler:false};this.bus.emit('farmChanged',{plot,crop,action:'plant'});this.bus.emit('materialsChanged');this.bus.emit('progressionChanged');return true}
  waterCrop(plot,boostSeconds=4){const slot=this.farm[plot];if(!slot?.crop)return false;const now=Date.now();slot.readyAt=Math.max(now,slot.readyAt-boostSeconds*1000);slot.wateredUntil=Math.max(slot.wateredUntil||0,now+6000);this.bus.emit('farmChanged',{plot,crop:slot.crop,action:'water'});this.bus.emit('progressionChanged');return true}
  harvestCrop(plot){const slot=this.farm[plot],c=this.data.jobs?.farm?.crops?.[slot?.crop];if(!c||Date.now()<slot.readyAt)return false;for(const [k,v] of Object.entries(c.yields||{}))this.materials[k]=(this.materials[k]||0)+v;const progress=this.jobs.farmer;progress.xp+=c.xp;while(progress.xp>=this.jobXpToNext('farmer')){progress.xp-=this.jobXpToNext('farmer');progress.level++}this.gold+=Number(c.gold||0);this.farm[plot]={crop:null,plantedAt:0,readyAt:0,wateredUntil:0,sprinkler:false};this.bus.emit('farmChanged',{plot,crop:c.id,action:'harvest',yields:c.yields,gold:Number(c.gold||0)});this.bus.emit('materialsChanged');this.bus.emit('progressionChanged');return true}
  resetRun(){this.bus.emit('runReset');this.bus.emit('progressionChanged')}
  resetAllProgression(){this.level=1;this.xp=0;this.gold=Number(this.data.startingGold||0);this.totalKills=0;this.totalDamage=0;this.bestWave=0;this.classId='ranger';this.skillPoints=0;this.skills={power:0,vitality:0,haste:0,precision:0};this.inventory=[];this.equipment={weapon:'training_bow',armor:null,ring:null};this.materials={scrap:0,crystal:0,ember:0,grain:8,herb:4,moonleaf:0};this.jobs={farmer:{level:1,xp:0},alchemist:{level:1,xp:0},miner:{level:1,xp:0},woodcutter:{level:1,xp:0}};this.farm=this.createFarm();this.bus.emit('progressionReset');this.bus.emit('progressionChanged')}
}
